name: Accessibility Tests
run-name: Accessibility Tests for ${{ github.sha }}
on:
  push:
    branches:
    - test-runner

jobs:
  accessibility-tests:
    runs-on: ubuntu-26.04
    env:
      PLAYWRIGHT_BASE_URL: ${{ github.event.inputs.mozorg_service_hostname || 'https://dev.bedrock.nonprod.webservices.mozgcp.net' }}
      CI: true
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: 24
    - name: Install dependencies
      run: cd tests/playwright && npm ci && npm run install-deps
    - name: Run accessibility tests
      run: cd tests/playwright && npm run a11y-tests
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a   # v7.0.1
      if: ${{ !cancelled() }}
      with:
        name: test-results-a11y-${{ github.sha }}
        path: tests/playwright/test-results-a11y/
        if-no-files-found: ignore  # this avoids a false "Warning" if there were no issues
        retention-days: 30

