name: Build and push a Docker image

on:
  push:
    branches:
      - main
      - stage
      - test-cd
    tags:
      - '*'

jobs:
  build_and_publish_public_images:
    name: Builder
    runs-on: ubuntu-latest

    steps:
      - name: Free space on the runner
        run: |
          docker system df
          echo "Free space:"
          df -h

      - name: Remove unused tools
        run: |
          #sudo rm -rf /usr/lib/jvm
          #sudo rm -rf /usr/share/dotnet
          #sudo rm -rf /usr/share/swift
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /opt/microsoft /opt/google
          sudo rm -rf /opt/az
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/.ghcup
          #sudo rm -rf /usr/local/julia*
          #sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /opt/hostedtoolcache/CodeQL

      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: "cache-from: type=gha cache-to: type=gha,mode=max"

      - uses: actions/checkout@v5
        with:
            fetch-depth: 10 # get enough so we have a Git history, but not everything
            fetch-tags: true
            ref: ${{ env.REF_ID }}

      - name: Free space before buildx
        run: |
          docker system df
          echo "Free space:"
          df -h

      - name: Build and push public images
        run: |
            ./bin/build-release-image.sh
        timeout-minutes: 90
        env:
            GIT_COMMIT: ${{ github.sha }}

      - name: Free space final
        if: always()
        run: |
          docker system df
          echo "Free space:"
          df -h
