name: Unit tests
on:
  push:
    branches:
      - test-ci
  pull_request:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Disk space on the runner
        run: |
          docker system df
          echo "Free space:"
          df -h

      - uses: actions/checkout@v4

      - name: "Run Python tests (on Docker)"
        run: |
            # FIXME: GitHub provides compose version enabling bake but timing out
            export COMPOSE_BAKE=false
            make clean test-image

      - name: Disk space after build
        run: |
          docker system df
          echo "Free space:"
          df -h
