name: Unit tests
on:
  push:
    branches:
      - test-ci
  pull_request:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Disk space on the runner
        run: |
          docker system df
          echo "Free space:"
          df -h

      - uses: actions/checkout@v4

      - name: "Test in Docker (+release build)"
        run: |
          make clean test-ci

      - name: Disk space after build
        run: |
          docker system df
          echo "Free space:"
          df -h
